# Data Representation in Natural Language Processing

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import gensim

In [130]:
tw_path = open("files/twData_clean.csv","r")
tw_data = pd.read_csv(tw_path, header=0, encoding = 'unicode_escape')
tweets = tw_data.TwContent.values

## 1. CountVectorize

In [131]:
def count_vec(text):
    vectorizer = CountVectorizer()
    vocabulary=vectorizer.fit(text)
    doc_term_matrix= vectorizer.transform(text)
    final=doc_term_matrix.toarray()
    
    return final

In [132]:
count_vec([tweets[212]])

array([[1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
        1]])

## 2. Word embedding

### 2.1 Making water corporus

In [133]:
#!pip install ipynb

In [134]:
from ipynb.fs.full.Water_nlp import clean_collection
import os
from nltk.corpus.reader.plaintext import PlaintextCorpusReader

In [135]:
corpusdir = 'corpus/'
if not os.path.isdir(corpusdir):
    os.mkdir(corpusdir)

In [136]:
# one file
def make_data_from_tweets(tweets):
    filename = 0
    file = open(corpusdir+'data.txt','a')
    for tw in tweets:
        file.write(tw)
        file.write('\n')
    file.close()

In [137]:
# seperate files
def make_text(data):
    filename = 0
    for text in data:
        print(text)
        filename+=1
        file = open(corpusdir+str(filename)+'.txt','w')
        file.write(text)#,encoding="UTF-8")
        file.close()

In [138]:
data = clean_collection(tweets, lem=True)

In [139]:
make_text(data)

les gouvernorats siliana kasserine jendouba souffrent coupures  eau potable
perturbations coupures  approvisionnement eau potable les gouvernorats siliana kasserine jendouba
lapprovisionnement eau potable reprendra nuit mardi mercredi
perturbations coupures  approvisionnement eau potable quelques régions jendouba béja
perturbations  approvisionnement eau potable quelques régions jendouba béjà
reprise progressive
tunisie perturbations coupures  approvisionnement eau potable jendouba béja
tunisie tozeur sonede rassure qualité  eau potable
gouvernants lhabitude prendre leau minérale pdt les populations quête leau potable les habitants dun village kenyan servi leau sale autorités lors dune réunion cela doit servir leçon tous centrafrique
jendouba nord vol équipements sonede prive plusieurs régions leau potable
vol équipements sonede prive plusieurs régions  eau potable
reprise cette nuit  approvisionnement eau potable région radès
selon communiqué sonede
malgré retard réalisation
ariana pe

capitale tunisienne abrite 7e assemblée générale réseau africain organismes bassin raob démarre mardi poursuivre jusquau 5 juillet sous signe réalisation vision africaine leau lhorizon 2025 amcowafrica oieau
quand linconscience mêle bêtise humaine
sidi bouzid plus 10 délégations sans eau après vandalisation conduites via webdotn tunisie
rt amina sœur compte les marques deau minérales tunisie jannet safia marwa ain oktor garci sabrine fourat
amina faut faire différence entre eau minérale naturelle eau source naturelle autres eau table eau plate
justryzeh processeur goutte deau
jy vais 6h leau froide a moins gens personne pisser côté cest propre commence bien journée
canicule si chacun met assiette balcon leau cela peut sauver milliers danimaux
eau paradisiaque beachgirl beachlife
pire  a a osé dire ah dégueu essuyés  eau culot
rt amina sœur compte les marques deau minérales tunisie jannet safia marwa ain oktor garci sabrine fourat
homersimpsm visite tunisie demande leau propose safia sa

In [140]:
newcorpus = PlaintextCorpusReader(corpusdir, '.*')

In [141]:
# cccess the plaintext; outputs pure string/basestring.
#newcorpus.raw().strip()

# Access paragraphs in the corpus. (list of list of list of strings)
# NOTE: NLTK automatically calls nltk.tokenize.sent_tokenize and 
#       nltk.tokenize.word_tokenize.
#
# Each element in the outermost list is a paragraph, and
# Each paragraph contains sentence(s), and
# Each sentence contains token(s)
#newcorpus.paras()
#newcorpus.paras(newcorpus.fileids()[43])

# Access sentences in the corpus. (list of list of strings)
# NOTE: That the texts are flattened into sentences that contains tokens.
#newcorpus.sents()
#newcorpus.sents(newcorpus.fileids()[103])

# Access just tokens/words in the corpus. (list of strings)
#newcorpus.words()
newcorpus.words(newcorpus.fileids()[305])

['gafsa', 'coupure', 'approvisionnement', 'eau', ...]

### 2.2 Word2Vec via gensim

In [142]:
from gensim.test.utils import common_texts

In [143]:
newcorpus.sents()

[['les', 'gouvernorats', 'siliana', 'kasserine', 'jendouba', 'souffrent', 'coupures', 'eau', 'potable'], ['jendouba', 'nord', 'vol', 'équipements', 'sonede', 'prive', 'plusieurs', 'régions', 'leau', 'potable'], ...]

In [144]:
model = gensim.models.Word2Vec(newcorpus.sents())

In [145]:
X= list(model.wv.vocab)
X

['les',
 'jendouba',
 'coupures',
 'eau',
 'potable',
 'nord',
 'vol',
 'équipements',
 'sonede',
 'plusieurs',
 'régions',
 'leau',
 'travaux',
 'rt',
 'électricité',
 'a',
 'bangui',
 'odilon236',
 'centrafrique',
 'gouvernement',
 'fait',
 'peu',
 'périphéries',
 'faut',
 'aussi',
 'tunisie',
 'prix',
 'enfants',
 'coupe',
 'pendant',
 'vie',
 'accès',
 'assainissement',
 'millions',
 'personnes',
 'sans',
 'dun',
 'dune',
 'mer',
 'avant',
 'deau',
 'chaque',
 'travers',
 'milliards',
 'cette',
 'droit',
 'reprise',
 'approvisionnement',
 'région',
 'toujours',
 'après',
 'via',
 'rouge',
 'selon',
 'peau',
 'plus',
 'besoin',
 'dhydratation',
 'peaux',
 'mature',
 'délicates',
 'sensibles',
 'fragiles',
 'voici',
 'bonheur',
 'rééquilibrante',
 'calmante',
 'adoucissante',
 'apaisante',
 'disponible',
 'immédiatement',
 'heures',
 'intestin',
 'ni',
 'beaucoup',
 'jamais',
 'rien',
 'cest',
 'ça',
 'sait',
 'reconnu',
 'ils',
 'nont',
 'acaweadvocate',
 'reportage',
 'mort',
 '4',

In [146]:
 model.wv['eau']

array([-2.1429969e-02, -2.1078310e-03,  4.2538114e-02,  1.0287820e-02,
        1.4368660e-02, -8.9158509e-03, -3.4731679e-02,  2.2725923e-02,
       -1.2648627e-02, -3.9628498e-02,  1.1406300e-02, -7.3769521e-03,
       -2.1374287e-02,  1.7921127e-02, -1.1380520e-02, -2.8312964e-02,
       -3.3381563e-02, -3.2697897e-03,  2.7204767e-05, -1.8693656e-02,
       -2.9897229e-03, -1.2347333e-02, -6.7138621e-03, -1.7997291e-02,
        1.2340487e-02, -1.0059533e-02,  1.9574257e-02, -3.0733090e-02,
        2.1645665e-02, -1.0635798e-02, -5.8916211e-03,  2.0355763e-02,
        1.6272755e-02,  6.8278173e-03,  1.5971106e-02,  1.8123290e-02,
       -2.5302049e-02, -2.0736270e-02,  8.1543764e-03, -4.6518646e-02,
       -7.5916559e-03, -6.2413383e-03,  5.1753535e-03,  1.9878330e-02,
       -1.1288807e-02,  2.6289973e-02,  5.7814820e-03, -1.6063316e-04,
        1.9945934e-02,  2.9849891e-02,  7.1950308e-03,  2.3378052e-02,
       -3.6135239e-03, -5.1534027e-03,  2.8558928e-03, -1.1212820e-02,
      

In [147]:
data=model.most_similar('eau')
data

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('potable', 0.9832545518875122),
 ('les', 0.9788177013397217),
 ('plus', 0.9779624938964844),
 ('faut', 0.9745000600814819),
 ('leau', 0.9700896739959717),
 ('sensibles', 0.9696218967437744),
 ('délicates', 0.9655733704566956),
 ('problème', 0.9648923873901367),
 ('mature', 0.9647103548049927),
 ('distribution', 0.9632799029350281)]

In [150]:
dissimlar_words = model.wv.doesnt_match('coupure eau potable'.split())
print(dissimlar_words)

coupure


/anaconda3/lib/python3.7/site-packages/gensim/models/keyedvectors.py:876: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  vectors = vstack(self.word_vec(word, use_norm=True) for word in used_words).astype(REAL)


In [151]:
def similarity_two_words(model,w1, w2):
    sim = model.wv.similarity(w1,w2)
    #print("The similarity between <{}> and <{}>: ".format(w1, w2), sim)
    return sim

In [152]:
similarity_two_words(model, 'eau', 'potable')

0.98325455

In [153]:
similarity_two_words(model, 'eau', 'coupure')

0.8854673

In [154]:
similarity_two_words(model, 'eau', 'jendouba')

0.7743771

In [155]:
similarity_two_words(model, 'eau', 'tunis')

0.930248

In [156]:
model2 = gensim.models.Word2Vec(newcorpus.sents(),window=2)

In [157]:
model2.wv['eau']

array([-8.6396830e-03, -3.6892067e-03,  1.3984810e-02,  4.5726625e-03,
        4.9488707e-03, -1.0600692e-03, -1.4834487e-02,  9.0062506e-03,
       -8.4275231e-03, -1.4006047e-02,  2.0561193e-03, -4.8339516e-03,
       -1.0254797e-02,  6.7594843e-03, -2.0376977e-03, -1.0073043e-02,
       -1.2101924e-02,  1.7034143e-03,  1.1690580e-03, -9.2493501e-03,
        2.0828252e-03, -5.2898983e-03, -3.3901962e-03, -7.1207117e-03,
        3.0114821e-03, -5.7446905e-03,  7.6343450e-03, -1.2439418e-02,
        1.0969409e-02, -5.7563665e-03, -2.8464631e-03,  1.0589947e-02,
        5.0841644e-03,  6.0663689e-03,  9.2930282e-03,  9.1709560e-03,
       -8.3375312e-03, -9.9844830e-03,  2.4285165e-03, -1.6954938e-02,
       -2.9335811e-03, -2.7889612e-03,  5.0623422e-03,  8.8550095e-03,
       -5.9121596e-03,  9.5540872e-03,  2.1686067e-03,  6.6362857e-04,
        4.7485325e-03,  1.2040647e-02,  1.9481865e-03,  1.1781148e-02,
        5.6563166e-04, -2.6295846e-04, -7.9428306e-04,  6.5603454e-05,
      

In [158]:
similarity_two_words(model2, 'eau', 'potable')

0.90062046

In [159]:
similarity_two_words(model2, 'eau', 'coupure')

0.6661516

In [160]:
similarity_two_words(model2, 'eau', 'tunis')

0.7503531

In [161]:
model2.wv.most_similar('eau')

[('potable', 0.9006204605102539),
 ('les', 0.8704516887664795),
 ('leau', 0.8577367663383484),
 ('faut', 0.8470708131790161),
 ('plus', 0.8416270017623901),
 ('tunisie', 0.8145299553871155),
 ('problème', 0.8098530769348145),
 ('a', 0.8068825006484985),
 ('cause', 0.7974146604537964),
 ('déshydratation', 0.7913922071456909)]

In [162]:
model.wv.most_similar('eau')

[('potable', 0.9832545518875122),
 ('les', 0.9788177013397217),
 ('plus', 0.9779624938964844),
 ('faut', 0.9745000600814819),
 ('leau', 0.9700896739959717),
 ('sensibles', 0.9696218967437744),
 ('délicates', 0.9655733704566956),
 ('problème', 0.9648923873901367),
 ('mature', 0.9647103548049927),
 ('distribution', 0.9632799029350281)]

### 2.3 Pre-trained word embedding

We use:
- google news --> doesn't cover French
- Godin word2vec for twitter https://fredericgodin.com/software/ 
--> Not adapted for tweets in French.
- fastText for french docs https://fasttext.cc/docs/en/support.html
--> Too general... not adapted to twitter or to the topic (water)

#### 2.3.1 GoogleNews

In [121]:
from gensim.models import KeyedVectors

In [124]:
path = '/Users/basho/fadouaproject/SafeWater/model/GoogleNews-vectors-negative300.bin'

In [125]:
model = KeyedVectors.load_word2vec_format(path, binary=True)

/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [126]:
vector = model['eau']

In [127]:
vector.shape

(300,)

In [128]:
sample = "tunisie perturbations coupures leau potable cités ettadhamen douar hicher reprise prévue soir selon sonede"

In [129]:
vectors = [model[x] for x in sample.split(' ')]

KeyError: "word 'tunisie' not in vocabulary"

#### 2.3.2 Godin model

In [29]:
from gensim.models import KeyedVectors

In [30]:
path = 'model/word2vec_twitter_model/word2vec_twitter_model.bin'

In [ ]:
model = KeyedVectors.load_word2vec_format(path, binary=True, unicode_errors='ignore')

/Users/Origami/anaconda3/lib/python3.6/site-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [ ]:
# Access vectors for specific words with a keyed lookup:
vector = model['eau']
#vector

In [43]:
vector.shape

AttributeError: 'list' object has no attribute 'shape'

In [44]:
#vector = model['gouvernorats'] # gouvernorats not included in the vocabulary. Godin word2vec is not for french language
#vector

#### 2.3.3 fastText

In [33]:
import fasttext

In [31]:
def make_data_from_tweets(tweets):
    filename = 0
    file = open('data.txt','a')
    for tw in tweets:
        file.write(tw)
    file.close()

In [32]:
#make_data_from_tweets(clean_collection(tweets, lem=True))

In [29]:
path = '/Users/basho/fadouaproject/SafeWater/model/cc.fr.300.bin'

# CBOW model
model = fasttext.cbow('data.txt', path)

# Access vectors for specific words with a keyed lookup:
#

In [30]:
vector = model['eau']
#vector

In [31]:
len(vector)

100

In [32]:
vector = model['gouvernorats']
#vector

In [33]:
vectors = [model[x] for x in [s for s in clean_collection(tweets, lem=True)]]

In [34]:
vectors=np.array(vectors)

In [35]:
embedding_matrix=np.vstack(vectors)
embedding_matrix

array([[ 0.01510056, -0.04534726, -0.02222504, ..., -0.03518727,
         0.15241031,  0.12867574],
       [ 0.01911572, -0.06287023, -0.03116055, ..., -0.04759455,
         0.20960853,  0.17671601],
       [ 0.01325244, -0.04773147, -0.02495549, ..., -0.03608626,
         0.16396153,  0.1380997 ],
       ...,
       [ 0.00328554, -0.00538237, -0.00224848, ..., -0.0023036 ,
         0.00906369,  0.00774935],
       [ 0.01953404, -0.07345748, -0.03722223, ..., -0.05470436,
         0.24624388,  0.20672752],
       [ 0.00290398, -0.00419246, -0.00149947, ..., -0.00213428,
         0.00539392,  0.00481484]])

In [36]:
embedding_matrix.shape

(286, 100)

In [37]:
model.cosine_similarity('eau','tunis')

0.9991000063539089

In [38]:
model.cosine_similarity('eau','coupure')

0.9998339438408912

In [39]:
model.cosine_similarity('eau','projet')

0.9994097436713149

In [40]:
model.cosine_similarity('eau','distribution')

0.9996437167357842

In [41]:
model.words #.difference('eau','coupure')

{'108',
 '12',
 '15',
 '19',
 '2',
 '20',
 '2010',
 '2019',
 '3',
 '35',
 '4',
 '5',
 '55',
 '611',
 '63',
 '70',
 '85rt',
 'a',
 'absorbe',
 'acaweadvocate',
 'accès',
 'adoucissante',
 'analysé',
 'annonce',
 'années',
 'ans',
 'antiâge',
 'apaisante',
 'apprend',
 'approvisionnement',
 'ariana',
 'arrêt',
 'assainissement',
 'astes',
 'augmentation',
 'augmente',
 'aujourd',
 'aussi',
 'autant',
 'autorités',
 'avant',
 'baie',
 'balbutiante',
 'bangui',
 'basé',
 'beaucoup',
 'besoin',
 'bien',
 'boire',
 'bonheur',
 'bouteille',
 'calmante',
 'cameroun',
 'canal',
 'candidat',
 'capacité',
 'casa',
 'centrafrique',
 'cest',
 'cette',
 'cettert',
 'chambres',
 'chercheurs',
 'choix',
 'chronique',
 'citoyens',
 'comme',
 'commun',
 'compose',
 'conrt',
 'consacrés',
 'contre',
 'coucher',
 'coupe',
 'coupure',
 'coupures',
 'crise',
 'cuisine',
 'deau',
 'demain',
 'denfants',
 'depuis',
 'dernières',
 'desserte',
 'desservant',
 'deux',
 'devient',
 'dhydratation',
 'dinars',
 'di

In [1]:
classifier = fasttext.supervised('/Users/basho/fadouaproject/SafeWater/data.txt', path)

NameError: name 'fasttext' is not defined

In [ ]:
result = classifier.test('Coupure deau prevue a Tunis et Ariana le soir')