# Data Representation in Natural Language Processing

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import gensim

In [2]:
tw_path = open("files/twData_clean.csv","r")
tw_data = pd.read_csv(tw_path, header=0, encoding = 'unicode_escape')
tweets = tw_data.TwContent.values

## 1. CountVectorize

In [42]:
def count_vec(text):
    vectorizer = CountVectorizer()
    vocabulary=vectorizer.fit(text)
    doc_term_matrix= vectorizer.transform(text)
    final=doc_term_matrix.toarray()
    
    return final

In [43]:
count_vec([tweets[212]])

array([[1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
        1]])

## 2. Word embedding

### 2.1 Making water corporus

In [44]:
#!pip install ipynb

In [45]:
from ipynb.fs.full.Water_nlp import clean_collection
import os
from nltk.corpus.reader.plaintext import PlaintextCorpusReader

[('perturbations', 'perturbation'), ('coupures', 'coupure'), (' ', ' '), ('approvisionnement', 'approvisionnemer'), ('eau', 'eau'), ('potable', 'potable'), ('quelques', 'quelque'), ('régions', 'région'), ('jendouba', 'jendouba'), ('béja', 'béjer')]
[(0, '0.028*"eau" + 0.025*"les"'), (1, '0.026*"eau" + 0.017*"rt"')]
tweet 1:  les gouvernorats siliana kasserine jendouba souffrent coupures  eau potable
tweet 2:  perturbations coupures  approvisionnement eau potable les gouvernorats siliana kasserine jendouba
tweet 1:  les gouvernorats siliana kasserine jendouba souffrent coupures  eau potable
tweet 2:  vol équipements sonede prive plusieurs régions  eau potable


In [49]:
corpusdir = 'corpus/'
#if not os.path.isdir(corpusdir):
#    os.mkdir(corpusdir)

In [ ]:
# one file
#def make_data_from_tweets(tweets):
#    filename = 0
#    file = open(corpusdir+'data.txt','a')
#    for tw in tweets:
#        file.write(tw)
#        file.write('\n')
#    file.close()

In [ ]:
# seperate files
#def make_text(data):
#    filename = 0
#    for text in data:
#        print(text)
#        filename+=1
#        file = open(corpusdir+str(filename)+'.txt','w')
#        file.write(text)#,encoding="UTF-8")
#        file.close()

In [46]:
data = clean_collection(tweets, lem=True)

In [51]:
#make_text(data)

In [50]:
newcorpus = PlaintextCorpusReader(corpusdir, '.*')

In [53]:
# cccess the plaintext; outputs pure string/basestring.
#newcorpus.raw().strip()

# Access paragraphs in the corpus. (list of list of list of strings)
# NOTE: NLTK automatically calls nltk.tokenize.sent_tokenize and 
#       nltk.tokenize.word_tokenize.
#
# Each element in the outermost list is a paragraph, and
# Each paragraph contains sentence(s), and
# Each sentence contains token(s)
#newcorpus.paras()
#newcorpus.paras(newcorpus.fileids()[43])

# Access sentences in the corpus. (list of list of strings)
# NOTE: That the texts are flattened into sentences that contains tokens.
#newcorpus.sents()
#newcorpus.sents(newcorpus.fileids()[103])

# Access just tokens/words in the corpus. (list of strings)
#newcorpus.words()
newcorpus.words(newcorpus.fileids()[436])

['sonede', 'annonce', 'coupures', 'perturbations', ...]

### 2.2 Word2Vec via gensim

In [54]:
from gensim.test.utils import common_texts

In [55]:
newcorpus.sents()

[['les', 'gouvernorats', 'siliana', 'kasserine', 'jendouba', 'souffrent', 'coupures', 'eau', 'potable'], ['jendouba', 'nord', 'vol', 'équipements', 'sonede', 'prive', 'plusieurs', 'régions', 'leau', 'potable'], ...]

In [56]:
model = gensim.models.Word2Vec(newcorpus.sents())

In [57]:
X= list(model.wv.vocab)
X

['les',
 'jendouba',
 'coupures',
 'eau',
 'potable',
 'nord',
 'vol',
 'équipements',
 'sonede',
 'plusieurs',
 'régions',
 'leau',
 'travaux',
 'rt',
 'électricité',
 'a',
 'bangui',
 'odilon236',
 'centrafrique',
 'gouvernement',
 'fait',
 'peu',
 'périphéries',
 'faut',
 'aussi',
 'tunisie',
 'prix',
 'enfants',
 'coupe',
 'pendant',
 'vie',
 'accès',
 'assainissement',
 'millions',
 'personnes',
 'sans',
 'dun',
 'dune',
 'mer',
 'avant',
 'deau',
 'chaque',
 'travers',
 'milliards',
 'cette',
 'droit',
 'reprise',
 'approvisionnement',
 'région',
 'toujours',
 'après',
 'via',
 'rouge',
 'selon',
 'peau',
 'plus',
 'besoin',
 'dhydratation',
 'peaux',
 'mature',
 'délicates',
 'sensibles',
 'fragiles',
 'voici',
 'bonheur',
 'rééquilibrante',
 'calmante',
 'adoucissante',
 'apaisante',
 'disponible',
 'immédiatement',
 'heures',
 'intestin',
 'ni',
 'beaucoup',
 'jamais',
 'rien',
 'cest',
 'ça',
 'sait',
 'reconnu',
 'ils',
 'nont',
 'acaweadvocate',
 'reportage',
 'mort',
 '4',

In [58]:
 model.wv['eau']

array([ 0.02063291, -0.01813338,  0.01086354,  0.0134434 ,  0.00915405,
        0.02108891,  0.01065617,  0.02074577,  0.00769985,  0.01990254,
       -0.02011178,  0.04297063,  0.02321118, -0.0059525 ,  0.03947753,
       -0.04503277, -0.01144692,  0.01881642,  0.04530437,  0.02835352,
       -0.00862471,  0.0201069 , -0.02188269, -0.00801855,  0.0052058 ,
        0.01359207, -0.03276923,  0.01789154,  0.01008898,  0.00985568,
       -0.03815207, -0.01423651, -0.00664299, -0.01027305,  0.01282784,
        0.0180391 , -0.01353645, -0.01564674, -0.00648039,  0.01461278,
       -0.01277952,  0.01446649,  0.00389796, -0.02902619, -0.02264229,
       -0.00277547, -0.00214725, -0.00998191,  0.02131425,  0.0018667 ,
       -0.01637993,  0.00223922,  0.0351385 , -0.01511417,  0.04726404,
        0.02909623, -0.00537001,  0.03337039,  0.00855758,  0.01612389,
       -0.01463716, -0.02014721, -0.02466839,  0.02300984, -0.00235936,
       -0.00975088,  0.01553993, -0.01757431,  0.02296903,  0.00

In [59]:
data=model.most_similar('eau')
data

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('les', 0.9797747135162354),
 ('potable', 0.97902512550354),
 ('plus', 0.976499617099762),
 ('faut', 0.96953284740448),
 ('leau', 0.9686856269836426),
 ('sensibles', 0.9647523164749146),
 ('deau', 0.9641631245613098),
 ('a', 0.9630036354064941),
 ('fragiles', 0.9612061977386475),
 ('devient', 0.9610947370529175)]

In [60]:
dissimlar_words = model.wv.doesnt_match('coupure eau potable'.split())
print(dissimlar_words)

coupure


/anaconda3/lib/python3.7/site-packages/gensim/models/keyedvectors.py:876: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  vectors = vstack(self.word_vec(word, use_norm=True) for word in used_words).astype(REAL)


In [61]:
def similarity_two_words(model,w1, w2):
    sim = model.wv.similarity(w1,w2)
    #print("The similarity between <{}> and <{}>: ".format(w1, w2), sim)
    return sim

In [62]:
similarity_two_words(model, 'eau', 'potable')

0.9790251

In [63]:
similarity_two_words(model, 'eau', 'coupure')

0.8811195

In [64]:
similarity_two_words(model, 'eau', 'jendouba')

0.80485207

In [65]:
similarity_two_words(model, 'eau', 'tunis')

0.9044895

In [66]:
model2 = gensim.models.Word2Vec(newcorpus.sents(),window=2)

In [67]:
model2.wv['eau']

array([ 9.4739236e-03, -5.0116261e-03,  5.6540160e-03,  1.8106102e-03,
        5.6086122e-03,  7.3115928e-03,  1.7290688e-03,  6.6596568e-03,
        1.1793569e-03,  1.1043334e-02, -4.0303310e-03,  1.8670447e-02,
        7.7683423e-03,  1.3546438e-03,  1.7171117e-02, -1.9719800e-02,
       -6.4198407e-03,  9.2797028e-03,  1.6096259e-02,  8.3550084e-03,
       -4.7245501e-03,  4.2333733e-03, -9.2747156e-03, -2.6546393e-03,
        4.7225147e-03,  8.1469510e-03, -1.4849348e-02,  7.6950905e-03,
        4.1096595e-05,  3.1721466e-03, -1.4527968e-02, -5.9980280e-03,
       -6.4899155e-05, -5.6579905e-03,  5.7013305e-03,  3.2243149e-03,
       -4.6917303e-03, -9.5418142e-03, -5.4423800e-03,  5.8823973e-03,
       -3.0356590e-03,  2.3061300e-03,  3.1461369e-03, -1.2997809e-02,
       -1.0747216e-02, -2.2088077e-03, -2.1110619e-03, -3.4852810e-03,
        9.3441484e-03, -1.1045738e-03, -6.5120934e-03,  2.1644083e-03,
        1.5114731e-02, -4.7778478e-03,  1.7627100e-02,  1.2173986e-02,
      

In [68]:
similarity_two_words(model2, 'eau', 'potable')

0.8692312

In [69]:
similarity_two_words(model2, 'eau', 'coupure')

0.60812277

In [70]:
similarity_two_words(model2, 'eau', 'tunis')

0.5900843

In [71]:
model2.wv.most_similar('eau')

[('les', 0.8799888491630554),
 ('potable', 0.869231104850769),
 ('leau', 0.8554626107215881),
 ('plus', 0.8459827303886414),
 ('sans', 0.8456719517707825),
 ('a', 0.8417167067527771),
 ('faut', 0.8225437998771667),
 ('tunisie', 0.8008747696876526),
 ('sous', 0.7780416011810303),
 ('jeunes', 0.7747730016708374)]

In [72]:
model.wv.most_similar('eau')

[('les', 0.9797747135162354),
 ('potable', 0.97902512550354),
 ('plus', 0.976499617099762),
 ('faut', 0.96953284740448),
 ('leau', 0.9686856269836426),
 ('sensibles', 0.9647523164749146),
 ('deau', 0.9641631245613098),
 ('a', 0.9630036354064941),
 ('fragiles', 0.9612061977386475),
 ('devient', 0.9610947370529175)]

### 2.3 Pre-trained word embedding

We use:
- google news --> doesn't cover French words
- Godin word2vec for twitter https://fredericgodin.com/software/ 
--> Not adapted for tweets in French.
- fastText for french docs https://fasttext.cc/docs/en/support.html
--> Too general... not adapted to twitter or to the topic (water)

#### 2.3.1 GoogleNews

In [121]:
from gensim.models import KeyedVectors

In [124]:
path = '/Users/basho/fadouaproject/SafeWater/model/GoogleNews-vectors-negative300.bin'

In [125]:
model = KeyedVectors.load_word2vec_format(path, binary=True)

/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [126]:
vector = model['eau']

In [127]:
vector.shape

(300,)

In [128]:
sample = "tunisie perturbations coupures leau potable cités ettadhamen douar hicher reprise prévue soir selon sonede"

In [129]:
vectors = [model[x] for x in sample.split(' ')]

KeyError: "word 'tunisie' not in vocabulary"

#### 2.3.2 Godin model

In [163]:
from gensim.models import KeyedVectors

In [164]:
path = '/Users/basho/fadouaproject/SafeWater/model/word2vec_twitter_model/word2vec_twitter_model.bin'

In [165]:
model = KeyedVectors.load_word2vec_format(path, binary=True, unicode_errors='ignore')

/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [166]:
# Access vectors for specific words with a keyed lookup:
vector = model['eau']
#vector

In [167]:
vector.shape

(400,)

In [168]:
vector = model['gouvernorats'] # gouvernorats not included in the vocabulary. Godin word2vec is not for french language
vector

KeyError: "word 'gouvernorats' not in vocabulary"

In [169]:
vectors = [model[x] for x in sample.split(' ')]
vectors

KeyError: "word 'coupures' not in vocabulary"

#### 2.3.3 fastText

In [3]:
import fasttext

In [30]:
#def make_data_from_tweets(tweets):
#    filename = 0
#    file = open('data.txt','a')
#    for tw in tweets:
#        file.write(tw)
#        file.write('\n')
#    file.close()

In [31]:
#filenames = ['file1.txt', 'file2.txt', ...]
#def collect_corpora(corpus, path,size=464):
#    with open(path, 'w') as outfile:
#        for i in range(1,size+1):
#            with open(corpus+str(i)+".txt") as infile:
#                outfile.write(infile.read())
#                outfile.write("\n")

In [32]:
 #collect_corpora("/Users/basho/fadouaproject2/water/corpus/","/Users/basho/fadouaproject2/water/data0807.txt")

In [33]:
#make_data_from_tweets(clean_collection(tweets, lem=True))

NameError: name 'clean_collection' is not defined

In [4]:
path = '/Users/basho/fadouaproject/SafeWater/model/cc.fr.300.bin'

# CBOW model
model = fasttext.cbow('data0807.txt', path)

# Access vectors for specific words with a keyed lookup:
#

In [5]:
vector = model['eau']
#vector

In [6]:
len(vector)

100

In [7]:
vector = model['gouvernorats']
vector

[0.0026333394926041365,
 0.0004583431000355631,
 0.0015618990873917937,
 -0.00040297824307344854,
 0.0009339713724330068,
 -0.0019025299698114395,
 0.00014381635992322117,
 -0.0005928538739681244,
 -0.0006212163134478033,
 -0.0003661340451799333,
 -9.695602784631774e-05,
 -0.00032445104443468153,
 0.00028244106215424836,
 0.0006108568049967289,
 -0.00011309773981338367,
 0.0002985682513099164,
 -0.0001528688590042293,
 0.0012167314998805523,
 0.0003845634637400508,
 -0.000994060654193163,
 0.0013144734548404813,
 -0.00022949010599404573,
 -0.0014799172058701515,
 0.002377656754106283,
 0.0006480717565864325,
 0.00016797886928543448,
 -0.0015981632750481367,
 -0.001310986583121121,
 -0.0005503213033080101,
 0.0013695774832740426,
 0.0020908555015921593,
 -0.0001683756709098816,
 0.0005655263084918261,
 -0.0006213497836142778,
 -0.0023903746623545885,
 -0.00043916067807003856,
 -0.00045638278243131936,
 -0.0009654165478423238,
 -0.0008394665201194584,
 -0.0016285899328067899,
 0.00177401

In [78]:
vectors = [model[x] for x in [s for s in clean_collection(tweets, lem=True)]]

In [79]:
vectors=np.array(vectors)

In [80]:
embedding_matrix=np.vstack(vectors)
embedding_matrix

array([[ 1.12798798e-03, -9.11411131e-04,  6.00925647e-04, ...,
        -2.04028678e-04,  3.56815406e-04,  4.45286023e-05],
       [ 1.61809835e-03, -5.67893614e-04,  1.28119544e-03, ...,
        -2.38617853e-04,  2.89702060e-04, -4.39771189e-04],
       [ 1.08614517e-03, -7.07134022e-04,  1.15271588e-03, ...,
        -8.15522508e-04,  1.47608735e-04, -8.02294817e-04],
       ...,
       [ 1.60457962e-03, -3.60681006e-04,  1.18202635e-03, ...,
         6.99559751e-05, -1.19417920e-04, -3.74757510e-04],
       [ 9.85771301e-04, -3.65581887e-04,  1.89663740e-04, ...,
         2.07624587e-04,  6.85874256e-04,  5.67355368e-04],
       [ 1.14639511e-03, -1.08763095e-04, -4.35829934e-05, ...,
         7.16942741e-05, -2.29802725e-04,  1.19460536e-04]])

In [81]:
embedding_matrix.shape

(464, 100)

In [82]:
model.cosine_similarity('eau','tunis')

0.8360370641277646

In [83]:
model.cosine_similarity('eau','coupure')

0.8111906809093568

In [84]:
model.cosine_similarity('eau','projet')

0.7806099860839453

In [85]:
model.cosine_similarity('eau','distribution')

0.866360430159756

In [86]:
model.words #.difference('eau','coupure')

{'19',
 '2',
 '2010',
 '2019',
 '21h',
 '24',
 '28',
 '35',
 '4',
 '55',
 '63',
 '70',
 '</s>',
 'a',
 'acaweadvocate',
 'accès',
 'adoucissante',
 'ain',
 'amina',
 'annonce',
 'apaisante',
 'approvisionnement',
 'après',
 'ariana',
 'assainissement',
 'aussi',
 'avant',
 'bangui',
 'beaucoup',
 'besoin',
 'bien',
 'boire',
 'bonheur',
 'bouteille',
 'calmante',
 'cameroun',
 'canal',
 'cause',
 'centrafrique',
 'cest',
 'cette',
 'chaque',
 'chez',
 'comme',
 'comment',
 'commun',
 'compose',
 'compte',
 'con',
 'conduites',
 'coupe',
 'coupure',
 'coupures',
 'deau',
 'demain',
 'depuis',
 'deux',
 'devient',
 'dhydratation',
 'dire',
 'disponible',
 'distribution',
 'doit',
 'domicile',
 'droit',
 'dun',
 'dune',
 'délavage',
 'délaver',
 'délicates',
 'dénombre',
 'déshydratation',
 'eau',
 'eaux',
 'el',
 'enfants',
 'face',
 'faire',
 'fait',
 'fatymdiallo',
 'faut',
 'fourat',
 'fragiles',
 'fréquente',
 'ftdes',
 'gafsa',
 'garci',
 'gens',
 'gouvernement',
 'grand',
 'grenoui

In [7]:
data = pd.read_csv('/Users/basho/fadouaproject2/water/data0807_labeled.csv',header=0)

In [8]:
train_tweets = pd.DataFrame(data)
train_tweets.shape

(442, 2)

In [9]:
file = open('data.train.txt', 'w+')
for i in train_tweets.index:
    if train_tweets["target"][i] == 1.0:
        line = '__label__'+str(1)+' '+train_tweets["tweet"][i]+'\n'
        file.write(line)
    else:
        line = '__label__'+str(0)+' '+train_tweets["tweet"][i]+'\n'
        file.write(line)
file.close()

In [10]:
classifier = fasttext.supervised('data.train.txt', path)

In [11]:
result = classifier.predict('Coupure deau prevue a Tunis et Ariana le soir')